export const equipmentBrands: Record<string, string[]> = {
  "Baggage Scanner": [
    "Smiths Detection",
    "Rapiscan Systems",
    "Nuctech",
    "L3Harris",
    "Analogic",
    "Astrophysics",
    "Gilardoni",
    "Scanna MSC",
  ],
  "WTMD": [
    "CEIA",
    "Garrett",
    "Smiths Detection",
    "Rapiscan Systems",
    "Nuctech",
  ],
  "HHMD": [
    "Garrett",
    "CEIA",
    "Smiths Detection",
    "Rapiscan Systems",
    "Nuctech",
  ],
  "ETD": [
    "Smiths Detection",
    "Rapiscan Systems",
    "Nuctech",
  ],
  "CCTV": [
    "Hikvision",
    "Dahua Technology",
    "Axis Communications",
    "Bosch",
    "Hanwha Vision",
    "UNV",
  ],
  "Road Barrier": [
    "FAAC",
    "CAME",
    "BFT",
    "Magnetic Autocontrol",
  ],
  "Road Blocker": [
    "FAAC",
    "CAME",
    "BFT",
    "Magnetic Autocontrol",
  ],
  "Access Control": [
    "HID",
    "Suprema",
    "ZKTeco",
    "Hikvision",
    "Dahua Technology",
  ],
  "Car Parking Management": [
    "SKIDATA",
    "DESIGNA",
    "Amano",
    "FAAC",
  ],
  "Bollard": [
    "FAAC",
    "CAME",
    "BFT",
    "Pilomat",
  ],
  "Human Body Scanner": [
    "Rohde & Schwarz",
    "Nuctech",
    "Smiths Detection",
    "L3Harris",
  ],
  "Walkie-Talkie": [
    "Motorola Solutions",
    "Hytera",
    "Kenwood",
    "Icom",
    "Tait",
  ],
};
